"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RecoilRoot } from "recoil";
import Nav_, { Search_ } from "./components/Nav_";
import Cart_ from "./components/Cart_";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faShoppingBag } from "@fortawesome/free-solid-svg-icons";
import Exit_ from "./components/Exit_";
import ExtraOptions_ from "./components/ExtraOptions_";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>UREMO</title>
      <body className={inter.className}>
        <RecoilRoot>
          {children}
          {/* <div
          className={`fixed top-0 w-full min-h-screen backdrop-blur-[30px] bg-white/50 flex flex-col justify-center items-center`}
        >
          <div
            className={`flex flex-row justify-center items-center relative overflow-hidden`}
          >
            <div
              className={`w-[150px] m-1 h-[500px] bg-black/60 hover:bg-black opacity-80 hover:opacity-100 rounded-[2px] cursor-pointer duration-1000 hover:duration-75 transition-all overflow-hidden shadow-sm`}
            >
              <img
                className={`object-cover w-full h-full`}
                src={`https://images.pexels.com/photos/4071422/pexels-photo-4071422.jpeg?auto=compress&cs=tinysrgb&w=1200`}
              />
            </div>
            <div
              className={`w-[180px] m-1 h-[550px] bg-black/80 hover:bg-black opacity-80 hover:opacity-100 rounded-[2px] cursor-pointer duration-1000 hover:duration-75 transition-all overflow-hidden shadow-sm`}
            >
              <img
                className={`object-cover w-full h-full`}
                src={`https://images.pexels.com/photos/2974113/pexels-photo-2974113.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2`}
              />
            </div>
            <div
              className={`w-[130px] m-1 h-[400px] bg-black/70 hover:bg-black rounded-[2px] opacity-80 hover:opacity-100 cursor-pointer duration-1000 hover:duration-75 transition-all overflow-hidden shadow-sm`}
            >
              <img
                className={`object-cover w-full h-full`}
                src={`https://images.pexels.com/photos/18846297/pexels-photo-18846297/free-photo-of-white-hen-running-in-the-yard.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2`}
              />
            </div>
            <div
              className={`absolute top-0 w-full h-full flex flex-col justify-end items-center pointer-events-none`}
            >
              <p className={`text-[30px] ml-6 font-black text-white`}>uREMO</p>
            </div>
          </div>
        </div> */}
          <Search_ />
          <Cart_/>
          <Nav_ />
          <Exit_ />
          <ExtraOptions_/>
        </RecoilRoot>
      </body>
    </html>
  );
}
